version: '3'

services:
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
      - "2003:2003"
      - "2004:2004"
      - "7002:7002"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - ./graphite/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
      - ./graphite/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    restart: always
    