apiVersion: 1

deleteDatasources:
  - name: Graphite
    orgId: 1

datasources:
  - name: Graphite
    type: graphite
    access: proxy
    orgId: 1
    url: http://statsd:80
    password: ''
    user: ''
    database: ''
    basicAuth: false
    basicAuthUser: ''
    basicAuthPassword: ''
    withCredentials: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      graphiteVersion: "1.1"
      httpMethod: "GET"
      keepCookies: []
    secureJsonFields: {}